artifact_location: file:///Users/mama18/Workspace/research/Telco-Customer-Churn-ML/mlrunsss/0
creation_time: 1766342248014
experiment_id: '0'
last_update_time: 1766342248014
lifecycle_stage: active
name: Default
